server:
  port: 8080

spring:
  profiles:
  active: dev
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/exam_2023?useUnicode=true&characterEncoding=utf8&autoReconnect=true&&serverTimezone=Asia/Seoul
      username: root
      password: