server:
  port: 8080

spring:
  profiles:
  active: dev
  datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mysql://117.111.10.96:3306/exam_2023?useUnicode=true&characterEncoding=utf8&autoReconnect=true&&serverTimezone=Asia/Seoul
      username: root
      password: